# Toolchain for building for Windows in Linux Host

# Dependencies
# mingw-w64

# 32-bit -> i686-w64-mingw32
# 64-bit -> x86_64-w64-mingw32

set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)

# set compilers
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-as)
set(CMAKE_ASM_MASM_COMPILER ${TOOLCHAIN_PREFIX}-as)
# set(CMAKE_ASM_COMPILER)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_PREFIX}-gfortran)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

# set target environment on host build system
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX};/usr/local/${TOOLCHAIN_PREFIX})
set(CMAKE_LIBRARY_PATH /usr/${TOOLCHAIN_PREFIX};/usr/local/${TOOLCHAIN_PREFIX})
set(CMAKE_PREFIX_PATH /usr/${TOOLCHAIN_PREFIX};/usr/local/${TOOLCHAIN_PREFIX})

# set install path
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX /usr/local/${TOOLCHAIN_PREFIX})
    set(CMAKE_INSTALL_BINDIR ${CMAKE_INSTALL_PREFIX}/bin)
    set(CMAKE_INSTALL_LIBDIR ${CMAKE_INSTALL_PREFIX}/lib)
    set(CMAKE_INSTALL_INCLUDEDIR ${CMAKE_INSTALL_PREFIX}/include)
    set(CMAKE_INSTALL_DATAROOTDIR ${CMAKE_INSTALL_PREFIX}/share)
endif()

# adjust behaviour of find commands
# look for header, libs in target environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)